version: "3.0"
services:
  nats:
    #image: nats-streaming:latest
    #command: -store file -dir datastore -cid "easer-tutorial-cluster" -m 8222 -V
    image: nats:latest
    command: -p 4222 --cluster_name "easer-tutorial-cluster" -m 8222 -js -V
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      easer-tutorial-network:
        aliases:
          - nats

networks:
  easer-tutorial-network:
